/**
 * An array of user data objects for the Twitty application.
 * Each object represents a user profile page with their details.
 */
export interface PageData {
  id: string;
  name: string;
  email: string;
  image: string;
  bgImage: string;
  bio: string;
  followers: number;
  following: number;
}

export const pages: PageData[] = [
  {
    id: "1",
    name: "Ramy Esam",
    email: "@ramyesam",
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    bgImage: "https://images.unsplash.com/photo-1503264116251-35a269479413",
    bio: "Waking up every day trying to understand life, coffee, and why socks disappear in the laundry. I tweet nonsense but sometimes it makes sense.",
    followers: 1250,
    following: 890,
  },
  {
    id: "2",
    name: "Laila Mostafa",
    email: "@lailaui",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
    bgImage: "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832_1280.jpg",
    bio: "UX lover, pizza addict. I collect tabs I’ll never read and overthink what to reply in casual conversations. Living on vibes and iced lattes.",
    followers: 2320,
    following: 1432,
  },
  {
    id: "3",
    name: "Ahmed Youssef",
    email: "@ahmedcodes",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    bgImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    bio: "I once walked into a glass door and said sorry. That sums me up. Always thinking, rarely tweeting, but I’m here if you need memes or deep thoughts.",
    followers: 310,
    following: 240,
  },
  {
    id: "4",
    name: "Sara Ali",
    email: "@saraa",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    bgImage: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61",
    bio: "Lover of plants, rainy mornings, and people who know how to hold a proper conversation. This is my digital corner for existential tweets and cat pics.",
    followers: 1800,
    following: 1150,
  },
  {
    id: "5",
    name: "Mohamed Salah",
    email: "@mosalah",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
    bgImage: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05",
    bio: "Here to share thoughts I can't say out loud. Yes, I’ve liked your tweet at 3AM while questioning my life choices. Peace & shawarma 🥙.",
    followers: 9850,
    following: 720,
  },
  {
    id: "6",
    name: "Nour Adel",
    email: "@nourwrites",
    image: "https://randomuser.me/api/portraits/women/19.jpg",
    bgImage: "https://images.unsplash.com/photo-1485217988980-11786ced9454",
    bio: "I keep switching between wanting to be invisible and wanting the whole world to read my tweets. Writer of randomness and daydreams.",
    followers: 1567,
    following: 1321,
  },
  {
    id: "7",
    name: "Kareem Nabil",
    email: "@kareemdaily",
    image: "https://randomuser.me/api/portraits/men/48.jpg",
    bgImage: "https://images.unsplash.com/photo-1493612276216-ee3925520721",
    bio: "Every day is a 'maybe I should move to the mountains' day. Retweeting chaos and pretending I’m organized.",
    followers: 220,
    following: 508,
  },
  {
    id: "8",
    name: "Yasmin Omar",
    email: "@yasmo",
    image: "https://randomuser.me/api/portraits/women/56.jpg",
    bgImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa",
    bio: "Multitasking between overthinking, drinking tea, and pretending to be busy. If you're reading this, hi. I’m a fan of your energy ✨",
    followers: 4020,
    following: 2010,
  },
  {
    id: "19",
    name: "Hana Farid",
    email: "@hanafarid",
    image: "https://randomuser.me/api/portraits/women/19.jpg",
    bgImage: "https://cdn.pixabay.com/photo/2016/11/29/08/41/apple-1868496_1280.jpg",
    bio: "Professional tea drinker and overthinker.",
    followers: 3098,
    following: 1784,
  },
  {
    id: "20",
    name: "Ahmed Samir",
    email: "@ahmedsamir",
    image: "https://randomuser.me/api/portraits/men/20.jpg",
    bgImage: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    bio: "Freelance photographer | Nature lover | Coffee in one hand, camera in the other.",
    followers: 3200,
    following: 150,
  },
  {
    id: "21",
    name: "Mona Hany",
    email: "@monahany",
    image: "https://randomuser.me/api/portraits/women/21.jpg",
    bgImage: "https://images.unsplash.com/photo-1517842645767-c639042777db",
    bio: "Digital marketer | Bookworm | Always learning. Turning ideas into strategies.",
    followers: 4500,
    following: 800,
  },
  {
    id: "22",
    name: "Karim Adel",
    email: "@karimadel",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
    bgImage: "https://images.unsplash.com/photo-1516542076529-1ea3854896f2",
    bio: "Software engineer | Gamer | Tech enthusiast. Coding my way through life.",
    followers: 6700,
    following: 1200,
  },
  {
    id: "23",
    name: "Yasmin Tarek",
    email: "@yasmintarek",
    image: "https://randomuser.me/api/portraits/women/23.jpg",
    bgImage: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    bio: "Graphic designer | Art lover | Coffee addict. Creating visuals that speak.",
    followers: 8900,
    following: 500,
  },
  {
    id: "24",
    name: "Omar Fathy",
    email: "@omarfathy",
    image: "https://randomuser.me/api/portraits/men/24.jpg",
    bgImage: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
    bio: "Travel blogger | Adventure seeker | Storyteller. Exploring the world one city at a time.",
    followers: 12500,
    following: 2000,
  },
  {
    id: "25",
    name: "Hana Sherif",
    email: "@hanasherif",
    image: "https://randomuser.me/api/portraits/women/25.jpg",
    bgImage: "https://images.unsplash.com/photo-1448375240586-882707db888b",
    bio: "Fitness trainer | Healthy lifestyle | Motivational speaker. Strong mind, stronger body.",
    followers: 9800,
    following: 300,
  },
  {
    id: "26",
    name: "Ali Hassan",
    email: "@alihassan",
    image: "https://randomuser.me/api/portraits/men/26.jpg",
    bgImage: "https://images.unsplash.com/photo-1517649763962-0c623066013b",
    bio: "Doctor | Researcher | Science lover. Saving lives and sharing knowledge.",
    followers: 7600,
    following: 400,
  },
  {
    id: "27",
    name: "Dalia Wael",
    email: "@daliawael",
    image: "https://randomuser.me/api/portraits/women/27.jpg",
    bgImage: "https://images.unsplash.com/photo-1517842645767-c639042777db",
    bio: "Interior designer | DIY enthusiast | Minimalist. Designing spaces that tell stories.",
    followers: 5400,
    following: 1200,
  },
  {
    id: "28",
    name: "Tarek Nour",
    email: "@tareknour",
    image: "https://randomuser.me/api/portraits/men/28.jpg",
    bgImage: "https://images.unsplash.com/photo-1516542076529-1ea3854896f2",
    bio: "Musician | Guitarist | Music producer. Creating melodies that touch the soul.",
    followers: 3200,
    following: 800,
  },
  {
    id: "29",
    name: "Nourhan Samy",
    email: "@nourhansamy",
    image: "https://randomuser.me/api/portraits/women/29.jpg",
    bgImage: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    bio: "Writer | Poet | Dreamer. Words are my paint, the world is my canvas.",
    followers: 4300,
    following: 600,
  },
  {
    id: "30",
    name: "Kareem Osama",
    email: "@kareemosama",
    image: "https://randomuser.me/api/portraits/men/30.jpg",
    bgImage: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
    bio: "Entrepreneur | Startup enthusiast | Risk-taker. Building the future one idea at a time.",
    followers: 8900,
    following: 1500,
  },
  {
    id: "31",
    name: "Salma Ahmed",
    email: "@salmaahmed",
    image: "https://randomuser.me/api/portraits/women/31.jpg",
    bgImage: "https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg",
    bio: "Fashion designer | Trendsetter | Creative mind. Style is a way to say who you are.",
    followers: 6700,
    following: 900,
  },
  {
    id: "32",
    name: "Hassan Mohamed",
    email: "@hassanmohamed",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    bgImage: "https://images.unsplash.com/photo-1517649763962-0c623066013b",
    bio: "Architect | Urban planner | Visionary. Designing the cities of tomorrow.",
    followers: 5400,
    following: 700,
  },
  {
    id: "33",
    name: "Farida Magdy",
    email: "@faridamagdy",
    image: "https://randomuser.me/api/portraits/women/33.jpg",
    bgImage: "https://images.unsplash.com/photo-1517842645767-c639042777db",
    bio: "Teacher | Educator | Lifelong learner. Shaping young minds for a better future.",
    followers: 3200,
    following: 500,
  },
  {
    id: "34",
    name: "Adel Ramadan",
    email: "@adelramadan",
    image: "https://randomuser.me/api/portraits/men/34.jpg",
    bgImage: "https://images.unsplash.com/photo-1516542076529-1ea3854896f2",
    bio: "Chef | Food lover | Culinary artist. Cooking is an art, and everyone eats.",
    followers: 7800,
    following: 1200,
  },
  {
    id: "35",
    name: "Lina Ashraf",
    email: "@linaashraf",
    image: "https://randomuser.me/api/portraits/women/35.jpg",
    bgImage: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    bio: "Journalist | Storyteller | Truth-seeker. Giving a voice to the voiceless.",
    followers: 6500,
    following: 900,
  },
  {
    id: "36",
    name: "Waleed Gamal",
    email: "@waleedgamal",
    image: "https://randomuser.me/api/portraits/men/36.jpg",
    bgImage: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
    bio: "Engineer | Problem solver | Innovator. Building solutions for a better world.",
    followers: 4300,
    following: 600,
  },
  {
    id: "37",
    name: "Aya Ibrahim",
    email: "@ayaibrahim",
    image: "https://randomuser.me/api/portraits/women/37.jpg",
    bgImage: "https://cdn.pixabay.com/photo/2016/11/29/08/41/apple-1868496_1280.jpg",
    bio: "Artist | Painter | Creative soul. Expressing emotions through colors and brushstrokes.",
    followers: 5600,
    following: 800,
  },
  {
    id: "38",
    name: "Mohamed Essam",
    email: "@mohamedessam",
    image: "https://randomuser.me/api/portraits/men/38.jpg",
    bgImage: "https://images.unsplash.com/photo-1517649763962-0c623066013b",
    bio: "Football player | Sports enthusiast | Team player. Chasing dreams on and off the field.",
    followers: 9800,
    following: 400,
  },
  {
    id: "39",
    name: "Rania Youssef",
    email: "@raniayoussef",
    image: "https://randomuser.me/api/portraits/women/39.jpg",
    bgImage: "https://images.unsplash.com/photo-1517842645767-c639042777db",
    bio: "Psychologist | Mental health advocate | Listener. Helping people find their inner peace.",
    followers: 7600,
    following: 1200,
  },
  {
    id: "40",
    name: "Amr Khalid",
    email: "@amrkhalid",
    image: "https://randomuser.me/api/portraits/men/40.jpg",
    bgImage: "https://images.unsplash.com/photo-1516542076529-1ea3854896f2",
    bio: "Filmmaker | Director | Storyteller. Capturing life's moments one frame at a time.",
    followers: 8900,
    following: 1500,
  },
];
