export const trendingData = [
  { id: 1, category: "Technology · Trending", title: "OpenAI", posts: "18K posts" },
  { id: 2, category: "Sports · Trending", title: "World Cup 2026", posts: "52K posts" },
  { id: 3, category: "Politics · Trending", title: "Elections 2024", posts: "30K posts" },
  { id: 4, category: "Entertainment · Trending", title: "The Witcher", posts: "12K posts" },
  { id: 5, category: "Business · Trending", title: "Bitcoin", posts: "45K posts" },
  { id: 6, category: "Technology · Trending", title: "ChatGPT", posts: "25K posts" },
  { id: 7, category: "Sports · Trending", title: "Olympics 2024", posts: "38K posts" },
  { id: 8, category: "Politics · Trending", title: "UN Summit", posts: "15K posts" },
  { id: 9, category: "Entertainment · Trending", title: "Stranger Things", posts: "42K posts" },
  { id: 10, category: "Business · Trending", title: "Tesla", posts: "33K posts" },
  { id: 11, category: "Technology · Trending", title: "Web3", posts: "28K posts" },
  { id: 12, category: "Sports · Trending", title: "Premier League", posts: "47K posts" },
  { id: 13, category: "Politics · Trending", title: "G20 Summit", posts: "19K posts" },
  { id: 14, category: "Entertainment · Trending", title: "Avatar 3", posts: "31K posts" },
  { id: 15, category: "Business · Trending", title: "Meta", posts: "22K posts" },
  { id: 16, category: "Technology · Trending", title: "5G Networks", posts: "36K posts" },
  { id: 17, category: "Sports · Trending", title: "NBA Finals", posts: "41K posts" },
  { id: 18, category: "Politics · Trending", title: "Climate Accord", posts: "27K posts" },
  { id: 19, category: "Entertainment · Trending", title: "Marvel Studios", posts: "53K posts" },
  { id: 20, category: "Business · Trending", title: "Amazon", posts: "39K posts" },
  { id: 21, category: "Technology · Trending", title: "Quantum Computing", posts: "17K posts" },
  { id: 22, category: "Sports · Trending", title: "UEFA Champions League", posts: "44K posts" },
  { id: 23, category: "Politics · Trending", title: "Brexit Update", posts: "21K posts" },
  { id: 24, category: "Entertainment · Trending", title: "House of the Dragon", posts: "48K posts" },
  { id: 25, category: "Business · Trending", title: "Google", posts: "34K posts" },
  { id: 26, category: "Technology · Trending", title: "Cybersecurity", posts: "29K posts" },
  { id: 27, category: "Sports · Trending", title: "F1 Racing", posts: "37K posts" },
  { id: 28, category: "Politics · Trending", title: "Midterm Elections", posts: "24K posts" },
  { id: 29, category: "Entertainment · Trending", title: "The Last of Us", posts: "46K posts" },
  { id: 30, category: "Business · Trending", title: "Microsoft", posts: "32K posts" },
  { id: 31, category: "Technology · Trending", title: "AR/VR", posts: "20K posts" },
  { id: 32, category: "Sports · Trending", title: "Wimbledon", posts: "43K posts" },
  { id: 33, category: "Politics · Trending", title: "NATO Summit", posts: "16K posts" },
  { id: 34, category: "Entertainment · Trending", title: "Star Wars", posts: "51K posts" },
  { id: 35, category: "Business · Trending", title: "Apple", posts: "40K posts" },
  { id: 36, category: "Technology · Trending", title: "Blockchain", posts: "26K posts" },
  { id: 37, category: "Sports · Trending", title: "Super Bowl", posts: "49K posts" },
  { id: 38, category: "Politics · Trending", title: "Refugee Crisis", posts: "23K posts" },
  { id: 39, category: "Entertainment · Trending", title: "Dune Part 2", posts: "54K posts" },
  { id: 40, category: "Business · Trending", title: "Netflix", posts: "35K posts" },
  { id: 41, category: "Technology · Trending", title: "IoT", posts: "18K posts" },
  { id: 42, category: "Sports · Trending", title: "Tour de France", posts: "45K posts" },
  { id: 43, category: "Politics · Trending", title: "Peace Talks", posts: "20K posts" },
  { id: 44, category: "Entertainment · Trending", title: "Wednesday", posts: "50K posts" },
  { id: 45, category: "Business · Trending", title: "Disney", posts: "38K posts" },
  { id: 46, category: "Technology · Trending", title: "Robotics", posts: "27K posts" },
  { id: 47, category: "Sports · Trending", title: "Australian Open", posts: "42K posts" },
  { id: 48, category: "Politics · Trending", title: "Trade Deal", posts: "22K posts" },
  { id: 49, category: "Entertainment · Trending", title: "Peaky Blinders", posts: "47K posts" },
  { id: 50, category: "Business · Trending", title: "Twitter", posts: "41K posts" }
];